### ISSUE TITLE
Reduced Movie Poster Heights for Improved Homepage Display

### ISSUE THREAD

**Issue by jayantghadge** [Alexandrbig1/movies-info#1]
### Issue Description:
 I noticed that the styling for images on mobile screens could be improved in your project. Improvements can be made to the movie poster images on the home page, adjusting their heights to ensure a more optimized display.

### Proposed Changes:
- Adjust the height of movie poster images to improve their fit within their respective containers.
- Maintain the aspect ratio of the original images for visual consistency.

### Request for Permission:
I'm planning to implement the following changes. Before creating a pull request, I'd like to get your approval.

**Comment by Alexandrbig1** [comment]
Hello, Thank you for checking my app, and ask approval before to change, i appreciate, that. But, can you provide a screenshots of the issue, cause i checked and the posters are fine, but if you have a better suggestions, please, be welcome, i appreciate!

**Comment by jayantghadge** [comment]
## Before Changes

The screenshot reveals that the movie name was cut off when viewed on a mobile screen.

**Screenshot (Before):**
![before](https://github.com/Alexandrbig1/movies-info/assets/88991259/b792d873-aae6-433c-9a41-1fce0be62f0a)

## After Changes

Following the adjustments made to the image height, the movie name is now clearly visible, and the image fits seamlessly within the container.

**Screenshot (After):**
![after](https://github.com/Alexandrbig1/movies-info/assets/88991259/75f40976-5c5f-4fd7-b68c-d3dd26216906)


I hope the provided screenshots effectively convey the details of the issue.

**Comment by Alexandrbig1** [comment]
Thank you! Yes, I see. You know, I've got this issue before, as i checked that api, from where im receiving the movies, the posters are not equal, there was a large posts and small, if i remember it well, or maybe i don't pay more attention for this issue.
If it's possible, before you want to contribute, and make changes, can you check that your changes apply for all the movies, and there no issue coming to that, what I found out when I did it. If so, and everything is good with your contribution, please, be welcome, I'll appreciate you contribution.
Thank you

**Comment by jayantghadge** [comment]
I fixed the issue by improving CSS styling. Each and every image now has exact aspect ratio needed for visual consistency. Can i raise a PR, so that you can check the changes and decide on whether to approve it or not?

**Comment by Alexandrbig1** [comment]
Yes, of course, you can merge, and I'll check it out. Thank you! Did you finished it with pure CSS or as all project is done by styled components?

**Comment by jayantghadge** [comment]
I just made changes to Global Style file and MovieList Component.

**Comment by Alexandrbig1** [comment]
Thank you for contributing. Appreciate! Great job!
